### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by XiaozhenQiao** [xiaobiaodu/MVGS#22]
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 101, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/app/MVGS/gaussian_renderer/__init__.py", line 85, in render
    rendered_image, radii = rasterizer(
ValueError: too many values to unpack (expected 2)

**Comment by XiaozhenQiao** [comment]
Reinstalled diff-gaussian-rasterization, then the above problem is solved, but now a new problem has appeared: 
Traceback (most recent call last):
File "train.py", line 280, in <module>
training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
File "train.py", line 125, in training
training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), testing_iterations, scene, render, (pipe, background))
File "train.py", line 250, in training_report
tb_writer.add_histogram("scene/opacity_histogram", scene.gaussians.get_opacity, iteration) File "/opt/conda/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 485, in add_histogram histogram(tag, values, bins, max_bins=max_bins), global_step, walltime File "/opt/conda/lib/python3.8/site-packages/torch/utils/tensorboard/sum mary.py", line 355, in histogram hist = make_histogram(values.astype(float), bins, max_bins) File "/opt/conda/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 399, in make_histogram raise ValueError("The histogram is empty, please file a bug report.") ValueError: The histogram is empty, please file file a bug report.

**Comment by XiaozhenQiao** [comment]
Also, I found that the rendered images were all white.
![image](https://github.com/user-attachments/assets/8f688175-5d71-47c2-b29d-4e717cfdd82f)
